#!/usr/bin/env node
const Koa = require('koa')
const app = new Koa()
const KoaRouter = require('koa-router')
const router = new KoaRouter()
const cors = require('koa2-cors')
const bodyparser = require('koa-bodyparser')
const staticKoa = require('koa-static')
const { exec } = require('child_process')

// 静态文件处理
app.use(staticKoa('../dist'))
app.use(staticKoa('../public'))

app.use(bodyparser())
// 跨域
app.use(cors({
  origin: function(ctx) {
    // 这里用 headers 和 header 属性皆可
    return ctx.header.origin
  }
}))

app.use(router.routes()) // 启动路由
app.use(router.allowedMethods())
app.listen(8090, console.log('http://localhost:8090'))
// 拿到当前系统的参数
const url = 'http://localhost:8090'
console.log('process.platform', process.platform)
switch (process.platform) {
  // mac系统使用 一下命令打开url在浏览器
  case 'darwin':
    exec(`open ${url}`)
    break
  // win系统使用 一下命令打开url在浏览器
  case 'win32':
    exec(`start ${url}`)
    break
  // 默认mac系统
  default:
    exec(`open ${url}`)
}
