#!/usr/bin/env node
const Koa = require('koa')
const app = new Koa()
const KoaRouter = require('koa-router')
const router = new KoaRouter()
const cors = require('koa2-cors')
const bodyparser = require('koa-bodyparser')
const staticKoa = require('koa-static')
const { exec } = require('child_process')

// 静态文件处理
app.use(staticKoa('../dist'))
app.use(staticKoa('../public'))

app.use(bodyparser())
// 跨域
app.use(cors({
  origin: function(ctx) {
    // 这里用 headers 和 header 属性皆可
    return ctx.header.origin
  }
}))

app.use(router.routes()) // 启动路由
app.use(router.allowedMethods())
app.listen(8090, console.log('http://localhost:8090'))
// 拿到当前系统的参数
const url = 'http://localhost:8090'
console.log('process.platform', process.platform)
switch (process.platform) {
  // mac系统使用 一下命令打开url在浏览器
  case 'darwin':
    exec(`open ${url}`)
    break
  // win系统使用 一下命令打开url在浏览器
  case 'win32':
    exec(`start ${url}`)
    break
  // 默认mac系统
  default:
    exec(`open ${url}`)
}

const tokens = {
  superadmin: {
    token: 'superadmin-token'
  },
  admin: {
    token: 'admin-token'
  },
  employees: {
    token: 'employees-token'
  }
}

const users = {
  'superadmin-token': {
    permission: [1],
    introduction: 'I am a super admin',
    name: '超级管理员'
  },
  'admin-token': {
    permission: [2],
    introduction: 'I am an admin',
    name: '管理员'
  },
  'employees-token': {
    permission: [3],
    introduction: 'I am an employees',
    name: '普通员工'
  }
}

const gamelist = {
  'data': [
    {
      'game_id': 123,
      'game_name': '牌圈1',
      'category_id': 2,
      'status': 1
    }
  ],
  'errno': '0'
}

// 游戏
router.get('/user/gamelist', ctx => {
  const info = gamelist['data']
  ctx.body = fhcode(info)
})

// 登入
router.post('/user/login', ctx => {
  const { username } = ctx.request.body
  const token = tokens[username]
  ctx.body = fhcode(token)
})

// 用户信息
router.post('/user/info', ctx => {
  const { token } = ctx.request.body
  const info = users[token]
  ctx.body = fhcode(info)
})

// 用户信息
router.get('/get/user/info', ctx => {
  const info = [{
    permission: [2],
    introduction: 'I am an admin',
    name: '管理员'
  }]
  ctx.body = fhcode(info)
})

function fhcode(obj, msg, code) {
  return {
    errno: code || '0',
    msg: msg || '操作成功！',
    data: obj || {}
  }
}
